# Generated by Django 5.2.5 on 2025-10-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cargas/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('resultado', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('moneda', models.CharField(max_length=3)),
                ('bolsa_nombre', models.CharField(max_length=100)),
                ('ley_bursatil', models.CharField(max_length=200)),
                ('texto_resumen', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('fecha_promulgacion', models.DateField()),
                ('url_oficial', models.URLField(blank=True)),
                ('tema', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normas', to='mercados.pais')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoNoInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('emisor', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_solicitud', models.DateField()),
                ('estado', models.CharField(default='En revisión', max_length=50)),
                ('pais_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.pais')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('NORMATIVA', 'Normativa'), ('TASA', 'Tasa tributaria'), ('LISTADO', 'Requisito de listado')], max_length=20)),
                ('descripcion', models.TextField()),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('pais_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.pais')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tasa_retencion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigente_desde', models.DateField()),
                ('comentarios', models.TextField(blank=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.pais')),
            ],
            options={
                'verbose_name_plural': 'calificaciones tributarias',
            },
        ),
    ]
