# Generated by Django 5.2.7 on 2025-10-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('moneda', models.CharField(default='CLP', max_length=3)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercados.instrumentonoinscrito')),
            ],
        ),
    ]
